name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Install dependencies
        working-directory: StepsDSL.Tests
        run: dotnet add package GitHubActionsTestLogger

      - name: Build & test
        working-directory: StepsDSL.Tests
        run: dotnet test --configuration Release --logger GitHubActions
